org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.java.installations.paths=/opt/jdks/java-17,/opt/jdks/java-21,/usr/lib/jvm/java-21-openjdk-amd64

minecraft_version=1.21.1
neo_version=21.1.256
mod_id=touhoutweaks
mod_name=TouhouTweaks
mod_version=1.4.0-r2
mod_group_id=io.github.h2sxxa.touhoutweaks
